### ISSUE TITLE
Grundlagen

### ISSUE THREAD

**Issue by skyfrk** [DHBW-VS-WI17B/assignment-abe1-b4#2]
- Wie funktioniert das Aktorenmodell?
  - Welches Problem wird gelöst?
  - Welche alternativen Lösungen gibt es?
  - Wie funktioniert es?
  - Ist das Aktorenmodell für dieses Problem eine gute Lösung?
- Entity Relationship Model mit [PlantUML](https://plantuml.com/class-diagram)
- Welche Aktoren bestehen?
- Welche Nachrichten werden verschickt?

**Comment by HuberJon** [comment]
@startuml
Event - Budget
Event - Customer

class Event {
identificationNumber: integer
eventName: String
date: date
location: string
price: int
}

class Customer{

}


@enduml

**Comment by HuberJon** [comment]
![image](https://user-images.githubusercontent.com/50103489/89873310-84678c00-dbba-11ea-980c-5adb0349b88a.png)
